### ISSUE TITLE
missing MIT license

### ISSUE THREAD

**Issue by lludlow** [charnet3d/plot_watcher#2]
submitted a PR, this should be enough
https://github.com/charnet3d/plot_watcher/pull/1

**Comment by lludlow** [comment]
could toss a link out to the source too http://timgolden.me.uk/python/index.html

**Comment by charnet3d** [comment]
Yeah thanks for the reminder. I added the specific how-to page where I got the change tracking code at the end of the README. I also updated the licence file to a more standard format.
