### ISSUE TITLE
not an issue, a question

### ISSUE THREAD

**Issue by josemanuelhda** [charnet3d/plot_watcher#3]
in the bat file you can choose the name of portable plots dir, but not the one for the old plots

only the name plots in the same level of directories is valid?

**Comment by josemanuelhda** [comment]
If I change the python script here:

 while 1:
    try:
      file_type, filename, action = files_changed.get_nowait ()
      ext = os.path.splitext(filename)[1]
      if (action == "Created" or "Renamed from" in action) and ext == ".plot":
        print("%s %s %s" % (file_type, filename, action))
        oldPlotDir = os.path.abspath(os.path.join(os.path.dirname(filename), "..", "Plots"))
        oldPlots = glob.glob(os.path.join(oldPlotDir, "*.plot"))
        if len(oldPlots) > 0:
          print("Removing {}".format(oldPlots[0]))
          os.remove(oldPlots[0])
        time.sleep (1)
    except queue.Empty:
      time.sleep (1)
      pass

and instead of "Plots" I write the name of my actual dir would it work?

**Comment by charnet3d** [comment]
if for each old plots directory you are going to make a new Portable_Plots dir then you can just rename the location in that line. I'll give you another example:

You have the old plots in these folders:

D:\AAA\BBB and E:\EEE\BBB

(The folders that contain the old plots need to have the same name or be in the root or the solution should be adapted for that specific case)

Then you can create 2 new folders where you put the new plots, say:

D:\AAA\New_Plots1 and E:\EEE\New_Plots2

So now you have to put these 2 folders in the .bat file:

python plot_watcher.py D:\AAA\New_Plots1,E:\EEE\New_Plots2

then edit the line in the py file to this:

oldPlotDir = os.path.abspath(os.path.join(os.path.dirname(filename), "..", "BBB"))

Another case is if you left the old plots in the root of the drive, and you just put the new plots in a directory then change the line to:

oldPlotDir = os.path.abspath(os.path.join(os.path.dirname(filename), ".."))

Hope it's clear enough, I didn't wanna spend too much time on the script but maybe I should have :p

**Comment by josemanuelhda** [comment]
thanks for the detailed explanation, the script is fine as it is, the only missing info I found was about the old plots dir, if you write in the readme that the old plots dir should be always named Plots, unless python code edited it should be clear

thanks again
